### ISSUE TITLE
Cannot build 1.21

### ISSUE THREAD

**Issue by dxxb** [ModusCreateOrg/evade2#338]
If I checkout version 1.21 (current master HEAD) and run cal.sh I get

```
make: *** No rule to make target `sound/evade2_00_intro.h', needed by `build-leonardo/Sound.cpp.o'.  Stop.
```

possible cause is 5df3417fbf4aaf86c2c7c00c87e35a26f8f1be82. Anyone else is seeing this?

**Comment by jaygarcia** [comment]
@dxxb Yes. There is an issue with pre-built object files. If you uncomment out the `make clean` command in cal.sh, the issue gets resolved.  IDK how else to resolve this as Sound.cpp doesn't require that file any more.

**Comment by dxxb** [comment]
Weird, when I tried running make clean manually the issue didn’t go away. I think the easiest way to fix this would be to run make clean in cal.sh

**Comment by jaygarcia** [comment]
`make clean` by itself won't work because the ARDUINO_DIR or whatever it is called is not passed to the make file.  The script does this for us easily :)

**Comment by dxxb** [comment]
Yep, I saw that after I wrote my previous comment. I have uncommented ```make clean``` in _cal.sh_ and all is good.
