### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by alexgleason** [ModusCreateOrg/evade2#342]
The readme says open source, though without clear boundaries people can't really know what they're allowed to do with it. You can [choose a license](https://choosealicense.com/) and add it to the repo. Team ARG usually picks MIT although I think GPL does a better job at preventing people from taking advantage of the work, because any improvements they make they're forced to share back.

**Comment by jaygarcia** [comment]
Hi @alexgleason thank you for this request.

We've added an MIT license, as it best suits the community.

https://github.com/ModusCreateOrg/evade2/pull/343
